

CREATE DATABASE "PhungLocCoffee"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_world.1258'
    LC_CTYPE = 'English_world.1258'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


CREATE TABLE CHINHANH (
    MaCN VARCHAR(20) PRIMARY KEY,
    TenCN VARCHAR(100),
    DiaChi VARCHAR(255),
    TrangThai INT, 
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP
);

CREATE TABLE DONVI (
    MaDV VARCHAR(20) PRIMARY KEY,
    TenDonVi VARCHAR(50),
    TrangThai INT,
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP
);


CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR(50) PRIMARY KEY,
    TenNCC VARCHAR(150),
    TrangThai INT,
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP
);

CREATE TABLE SANPHAM (
    MaSP VARCHAR(50) PRIMARY KEY,
    TenSP VARCHAR(150),
    GiaHienTai DECIMAL(18,0),
    IsTopping BOOLEAN, 
    TrangThai INT,
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(50) PRIMARY KEY,
    Username VARCHAR(50) UNIQUE,
    PasswordHash VARCHAR(255),
    TenNV VARCHAR(100),
    ChucVu VARCHAR(20),
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    TrangThai INT,
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP
);

CREATE TABLE NGUYENLIEU (
    MaNL VARCHAR(50) PRIMARY KEY,
    TenNL VARCHAR(150),
    DonViCoBan VARCHAR(20) REFERENCES DONVI(MaDV),
    TonToiThieu DECIMAL(18,2),
    TrangThai INT,
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP
);


CREATE TABLE NGUYENLIEU_DONVI (
    MaNL VARCHAR(50) REFERENCES NGUYENLIEU(MaNL),
    MaDV VARCHAR(20) REFERENCES DONVI(MaDV),
    PRIMARY KEY (MaNL, MaDV)
);

CREATE TABLE QUYDOIDONVI (
    MaDV_From VARCHAR(20) REFERENCES DONVI(MaDV),
    MaDV_To VARCHAR(20) REFERENCES DONVI(MaDV),
    TyLeQuyDoi DECIMAL(18,4),
    TrangThai INT,
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP,
    PRIMARY KEY (MaDV_From, MaDV_To)
);

CREATE TABLE PHIENBANCONGTHUC (
    MaPB VARCHAR(50) PRIMARY KEY,
    MaSP VARCHAR(50) REFERENCES SANPHAM(MaSP),
    NgayHieuLuc TIMESTAMP,
    TrangThai INT, 
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP
);

CREATE TABLE DINHMUCCONGTHUC (
    MaPB VARCHAR(50) REFERENCES PHIENBANCONGTHUC(MaPB),
    MaNL VARCHAR(50) REFERENCES NGUYENLIEU(MaNL),
    SoLuong DECIMAL(18,4),
    PRIMARY KEY (MaPB, MaNL)
);

CREATE TABLE CALAMVIEC (
    MaCa VARCHAR(50) PRIMARY KEY,
    MaNV VARCHAR(50) REFERENCES NHANVIEN(MaNV),
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    ThoiGianMo TIMESTAMP,
    ThoiGianDong TIMESTAMP NULL,
    TienDauCa DECIMAL(18,0),
    TienCuoiCa DECIMAL(18,0),
    SoTienThatThoat DECIMAL(18,0),
    LyDoGiaiTrinh VARCHAR(255) NULL,
    IsSynced BOOLEAN,
    CreatedAt TIMESTAMP
);


CREATE TABLE HOADON (
    MaHD VARCHAR(50) PRIMARY KEY,
    MaCa VARCHAR(50) REFERENCES CALAMVIEC(MaCa),
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    TongTien DECIMAL(18,0),
    TrangThai INT, 
    IsSynced BOOLEAN,
    CreatedAt TIMESTAMP
);


CREATE TABLE CTHD (
    ID VARCHAR(50) PRIMARY KEY,
    MaHD VARCHAR(50) REFERENCES HOADON(MaHD),
    MaSP VARCHAR(50) REFERENCES SANPHAM(MaSP),
    IDMonChinh VARCHAR(50) NULL REFERENCES CTHD(ID), 
    SoLuong INT,
    GiaBanTaiThoiDiem DECIMAL(18,0),
    GhiChu VARCHAR(255) NULL
);


CREATE TABLE THANHTOAN (
    MaTT VARCHAR(50) PRIMARY KEY,
    MaHD VARCHAR(50) REFERENCES HOADON(MaHD),
    PhuongThuc VARCHAR(20),
    SoTien DECIMAL(18,0),
    TrangThai INT,
    IsSynced BOOLEAN,
    CreatedAt TIMESTAMP
);

CREATE TABLE TONKHO (
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    MaNL VARCHAR(50) REFERENCES NGUYENLIEU(MaNL),
    SoLuongTon DECIMAL(18,2),
    PRIMARY KEY (MaCN, MaNL)
);

CREATE TABLE LOHANG (
    MaLo VARCHAR(50) PRIMARY KEY,
    MaNL VARCHAR(50) REFERENCES NGUYENLIEU(MaNL),
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    NgayNhap TIMESTAMP,
    HSD DATE,
    SoLuongCon DECIMAL(18,2),
    IsSynced BOOLEAN
);

CREATE TABLE KIEMKHO (
    MaKK VARCHAR(50) PRIMARY KEY,
    MaNV VARCHAR(50) REFERENCES NHANVIEN(MaNV),
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    NgayKiem TIMESTAMP,
    IsSynced BOOLEAN,
    CreatedAt TIMESTAMP
);

CREATE TABLE CTKK (
    MaKK VARCHAR(50) REFERENCES KIEMKHO(MaKK),
    MaNL VARCHAR(50) REFERENCES NGUYENLIEU(MaNL),
    SoLuongHeThong DECIMAL(18,2),
    SoLuongThucTe DECIMAL(18,2),
    ChenhLech DECIMAL(18,2),
    PRIMARY KEY (MaKK, MaNL)
);

CREATE TABLE PHIEUNHAP (
    MaPN VARCHAR(50) PRIMARY KEY,
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    MaNV VARCHAR(50) REFERENCES NHANVIEN(MaNV),
    MaNCC VARCHAR(50) REFERENCES NHACUNGCAP(MaNCC),
    TongTien DECIMAL(18,0),
    NgayNhap TIMESTAMP,
    TrangThai INT,
    IsSynced BOOLEAN,
    CreatedAt TIMESTAMP
);

CREATE TABLE CTPN (
    MaPN VARCHAR(50) REFERENCES PHIEUNHAP(MaPN),
    MaLo VARCHAR(50) REFERENCES LOHANG(MaLo),
    SoLuong DECIMAL(18,2),
    DonGiaNhap DECIMAL(18,0),
    ThanhTien DECIMAL(18,0),
    PRIMARY KEY (MaPN, MaLo)
);

CREATE TABLE PHIEUXUAT (
    MaPX VARCHAR(50) PRIMARY KEY,
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    MaNV VARCHAR(50) REFERENCES NHANVIEN(MaNV),
    LyDo VARCHAR(255),
    TrangThai INT,
    IsSynced BOOLEAN,
    CreatedAt TIMESTAMP
);

CREATE TABLE CTPX (
    MaPX VARCHAR(50) REFERENCES PHIEUXUAT(MaPX),
    MaLo VARCHAR(50) REFERENCES LOHANG(MaLo),
    SoLuong DECIMAL(18,2),
    PRIMARY KEY (MaPX, MaLo)
);

CREATE TABLE PHIEUCHUYEN (
    MaPC VARCHAR(50) PRIMARY KEY,
    MaCN_Xuat VARCHAR(20) REFERENCES CHINHANH(MaCN),
    MaCN_Nhap VARCHAR(20) REFERENCES CHINHANH(MaCN),
    MaNV VARCHAR(50) REFERENCES NHANVIEN(MaNV),
    TrangThai INT, 
    IsSynced BOOLEAN,
    CreatedAt TIMESTAMP
);

CREATE TABLE CTPC (
    MaPC VARCHAR(50) REFERENCES PHIEUCHUYEN(MaPC),
    MaLo VARCHAR(50) REFERENCES LOHANG(MaLo),
    SoLuong DECIMAL(18,2),
    PRIMARY KEY (MaPC, MaLo)
);

CREATE TABLE INVENTORYTRANSACTION (
    MaTrans VARCHAR(50) PRIMARY KEY,
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    MaNL VARCHAR(50) REFERENCES NGUYENLIEU(MaNL),
    MaLo VARCHAR(50) NULL REFERENCES LOHANG(MaLo),
    LoaiChungTu VARCHAR(20),
    IDChungTu VARCHAR(50),
    LoaiGiaoDich INT,
    SoLuong DECIMAL(18,2),
    TrangThai INT,
    IsSynced BOOLEAN,
    CreatedAt TIMESTAMP
);

CREATE TABLE SYNCLOG (
    SyncID VARCHAR(50) PRIMARY KEY,
    ThucThe VARCHAR(50),
    RecordID VARCHAR(50),
    GhiChu TEXT
);

CREATE TABLE CONFLICTLOG (
    ConflictID VARCHAR(50) PRIMARY KEY,
    DataLocal JSONB,
    DataServer JSONB
);