/* =========================================================
   CONSTRAINT MODULE - PHUNG LOC COFFEE - POSTGRESQL
   ========================================================= */


/* =========================================================
   1. CHI NHÁNH
   ========================================================= */

ALTER TABLE CHINHANH DROP CONSTRAINT IF EXISTS CK_CHINHANH_TRANGTHAI;
ALTER TABLE CHINHANH
ADD CONSTRAINT CK_CHINHANH_TRANGTHAI
CHECK (TrangThai IN (0, 1));

ALTER TABLE CHINHANH DROP CONSTRAINT IF EXISTS CK_CHINHANH_TEN_NOT_EMPTY;
ALTER TABLE CHINHANH
ADD CONSTRAINT CK_CHINHANH_TEN_NOT_EMPTY
CHECK (LENGTH(TRIM(TenCN)) > 0);

ALTER TABLE CHINHANH DROP CONSTRAINT IF EXISTS UQ_CHINHANH_TEN;
ALTER TABLE CHINHANH
ADD CONSTRAINT UQ_CHINHANH_TEN
UNIQUE (TenCN);


/* =========================================================
   2. ĐƠN VỊ
   ========================================================= */

ALTER TABLE DONVI DROP CONSTRAINT IF EXISTS CK_DONVI_TRANGTHAI;
ALTER TABLE DONVI
ADD CONSTRAINT CK_DONVI_TRANGTHAI
CHECK (TrangThai IN (0, 1));

ALTER TABLE DONVI DROP CONSTRAINT IF EXISTS CK_DONVI_TEN_NOT_EMPTY;
ALTER TABLE DONVI
ADD CONSTRAINT CK_DONVI_TEN_NOT_EMPTY
CHECK (LENGTH(TRIM(TenDonVi)) > 0);

ALTER TABLE DONVI DROP CONSTRAINT IF EXISTS UQ_DONVI_TEN;
ALTER TABLE DONVI
ADD CONSTRAINT UQ_DONVI_TEN
UNIQUE (TenDonVi);


/* =========================================================
   3. NHÀ CUNG CẤP
   ========================================================= */

ALTER TABLE NHACUNGCAP DROP CONSTRAINT IF EXISTS CK_NHACUNGCAP_TRANGTHAI;
ALTER TABLE NHACUNGCAP
ADD CONSTRAINT CK_NHACUNGCAP_TRANGTHAI
CHECK (TrangThai IN (0, 1));

ALTER TABLE NHACUNGCAP DROP CONSTRAINT IF EXISTS CK_NHACUNGCAP_TEN_NOT_EMPTY;
ALTER TABLE NHACUNGCAP
ADD CONSTRAINT CK_NHACUNGCAP_TEN_NOT_EMPTY
CHECK (LENGTH(TRIM(TenNCC)) > 0);

ALTER TABLE NHACUNGCAP DROP CONSTRAINT IF EXISTS UQ_NHACUNGCAP_TEN;
ALTER TABLE NHACUNGCAP
ADD CONSTRAINT UQ_NHACUNGCAP_TEN
UNIQUE (TenNCC);


/* =========================================================
   4. SẢN PHẨM
   ========================================================= */

ALTER TABLE SANPHAM DROP CONSTRAINT IF EXISTS CK_SANPHAM_TRANGTHAI;
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SANPHAM_TRANGTHAI
CHECK (TrangThai IN (0, 1));

ALTER TABLE SANPHAM DROP CONSTRAINT IF EXISTS CK_SANPHAM_GIA;
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SANPHAM_GIA
CHECK (GiaHienTai >= 0);

ALTER TABLE SANPHAM DROP CONSTRAINT IF EXISTS CK_SANPHAM_TEN_NOT_EMPTY;
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SANPHAM_TEN_NOT_EMPTY
CHECK (LENGTH(TRIM(TenSP)) > 0);

ALTER TABLE SANPHAM DROP CONSTRAINT IF EXISTS UQ_SANPHAM_TEN;
ALTER TABLE SANPHAM
ADD CONSTRAINT UQ_SANPHAM_TEN
UNIQUE (TenSP);


/* =========================================================
   5. KHUYẾN MÃI
   ========================================================= */

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_LOAI;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_LOAI
CHECK (LoaiKM IN ('PERCENT', 'AMOUNT'));

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_GIATRI;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_GIATRI
CHECK (GiaTri > 0);

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_PERCENT;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_PERCENT
CHECK (
    LoaiKM <> 'PERCENT'
    OR GiaTri <= 100
);

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_DIEUKIEN;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_DIEUKIEN
CHECK (DieuKienToiThieu >= 0);

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_GIAMTOIDA;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_GIAMTOIDA
CHECK (
    GiaTriGiamToiDa IS NULL
    OR GiaTriGiamToiDa >= 0
);

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_SOLUONG;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_SOLUONG
CHECK (
    SoLuong IS NULL
    OR SoLuong >= 0
);

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_DADUNG;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_DADUNG
CHECK (SoLuongDaDung >= 0);

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_DADUNG_KHONGVUOT_SOLUONG;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_DADUNG_KHONGVUOT_SOLUONG
CHECK (
    SoLuong IS NULL
    OR SoLuongDaDung <= SoLuong
);

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_THOIGIAN;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_THOIGIAN
CHECK (NgayKetThuc > NgayBatDau);

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_TRANGTHAI;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_TRANGTHAI
CHECK (TrangThai IN (0, 1));

ALTER TABLE KHUYENMAI DROP CONSTRAINT IF EXISTS CK_KHUYENMAI_TEN_NOT_EMPTY;
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_KHUYENMAI_TEN_NOT_EMPTY
CHECK (LENGTH(TRIM(TenKM)) > 0);


/* =========================================================
   6. NHÂN VIÊN
   ========================================================= */

ALTER TABLE NHANVIEN DROP CONSTRAINT IF EXISTS CK_NHANVIEN_TRANGTHAI;
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_NHANVIEN_TRANGTHAI
CHECK (TrangThai IN (0, 1));

ALTER TABLE NHANVIEN DROP CONSTRAINT IF EXISTS CK_NHANVIEN_TEN_NOT_EMPTY;
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_NHANVIEN_TEN_NOT_EMPTY
CHECK (LENGTH(TRIM(TenNV)) > 0);


/* =========================================================
   7. TÀI KHOẢN
   ========================================================= */

ALTER TABLE TAIKHOAN DROP CONSTRAINT IF EXISTS CK_TAIKHOAN_VAITRO;
ALTER TABLE TAIKHOAN
ADD CONSTRAINT CK_TAIKHOAN_VAITRO
CHECK (
    VaiTro IN (
        'ADMIN',
        'QUANLY_CHINHANH',
        'NHANVIEN_BANHANG',
        'NHANVIEN_KHO',
        'KETOAN'
    )
);

ALTER TABLE TAIKHOAN DROP CONSTRAINT IF EXISTS CK_TAIKHOAN_TRANGTHAI;
ALTER TABLE TAIKHOAN
ADD CONSTRAINT CK_TAIKHOAN_TRANGTHAI
CHECK (TrangThai IN (0, 1));

ALTER TABLE TAIKHOAN DROP CONSTRAINT IF EXISTS CK_TAIKHOAN_USERNAME_NOT_EMPTY;
ALTER TABLE TAIKHOAN
ADD CONSTRAINT CK_TAIKHOAN_USERNAME_NOT_EMPTY
CHECK (LENGTH(TRIM(Username)) >= 4);

ALTER TABLE TAIKHOAN DROP CONSTRAINT IF EXISTS CK_TAIKHOAN_PASSWORD_NOT_EMPTY;
ALTER TABLE TAIKHOAN
ADD CONSTRAINT CK_TAIKHOAN_PASSWORD_NOT_EMPTY
CHECK (LENGTH(TRIM(PasswordHash)) > 0);

ALTER TABLE TAIKHOAN DROP CONSTRAINT IF EXISTS UQ_TAIKHOAN_USERNAME;
ALTER TABLE TAIKHOAN
ADD CONSTRAINT UQ_TAIKHOAN_USERNAME
UNIQUE (Username);

ALTER TABLE TAIKHOAN DROP CONSTRAINT IF EXISTS UQ_TAIKHOAN_MANV;
ALTER TABLE TAIKHOAN
ADD CONSTRAINT UQ_TAIKHOAN_MANV
UNIQUE (MaNV);


/* =========================================================
   8. NGUYÊN LIỆU
   ========================================================= */

ALTER TABLE NGUYENLIEU DROP CONSTRAINT IF EXISTS CK_NGUYENLIEU_TONTOITHIEU;
ALTER TABLE NGUYENLIEU
ADD CONSTRAINT CK_NGUYENLIEU_TONTOITHIEU
CHECK (TonToiThieu >= 0);

ALTER TABLE NGUYENLIEU DROP CONSTRAINT IF EXISTS CK_NGUYENLIEU_TRANGTHAI;
ALTER TABLE NGUYENLIEU
ADD CONSTRAINT CK_NGUYENLIEU_TRANGTHAI
CHECK (TrangThai IN (0, 1));

ALTER TABLE NGUYENLIEU DROP CONSTRAINT IF EXISTS CK_NGUYENLIEU_TEN_NOT_EMPTY;
ALTER TABLE NGUYENLIEU
ADD CONSTRAINT CK_NGUYENLIEU_TEN_NOT_EMPTY
CHECK (LENGTH(TRIM(TenNL)) > 0);

ALTER TABLE NGUYENLIEU DROP CONSTRAINT IF EXISTS UQ_NGUYENLIEU_TEN;
ALTER TABLE NGUYENLIEU
ADD CONSTRAINT UQ_NGUYENLIEU_TEN
UNIQUE (TenNL);


/* =========================================================
   9. QUY ĐỔI ĐƠN VỊ
   ========================================================= */

ALTER TABLE QUYDOIDONVI DROP CONSTRAINT IF EXISTS CK_QUYDOI_TYLE;
ALTER TABLE QUYDOIDONVI
ADD CONSTRAINT CK_QUYDOI_TYLE
CHECK (TyLeQuyDoi > 0);

ALTER TABLE QUYDOIDONVI DROP CONSTRAINT IF EXISTS CK_QUYDOI_TRANGTHAI;
ALTER TABLE QUYDOIDONVI
ADD CONSTRAINT CK_QUYDOI_TRANGTHAI
CHECK (TrangThai IN (0, 1));

ALTER TABLE QUYDOIDONVI DROP CONSTRAINT IF EXISTS CK_QUYDOI_KHAC_DONVI;
ALTER TABLE QUYDOIDONVI
ADD CONSTRAINT CK_QUYDOI_KHAC_DONVI
CHECK (MaDV_From <> MaDV_To);


/* =========================================================
   10. PHIÊN BẢN CÔNG THỨC
   ========================================================= */

ALTER TABLE PHIENBANCONGTHUC DROP CONSTRAINT IF EXISTS CK_PBCT_TRANGTHAI;
ALTER TABLE PHIENBANCONGTHUC
ADD CONSTRAINT CK_PBCT_TRANGTHAI
CHECK (TrangThai IN (0, 1));


/* =========================================================
   11. ĐỊNH MỨC CÔNG THỨC
   ========================================================= */

ALTER TABLE DINHMUCCONGTHUC DROP CONSTRAINT IF EXISTS CK_DINHMUC_SOLUONG;
ALTER TABLE DINHMUCCONGTHUC
ADD CONSTRAINT CK_DINHMUC_SOLUONG
CHECK (SoLuong > 0);


/* =========================================================
   12. CA LÀM VIỆC
   ========================================================= */

ALTER TABLE CALAMVIEC DROP CONSTRAINT IF EXISTS CK_CALAMVIEC_TIEN;
ALTER TABLE CALAMVIEC
ADD CONSTRAINT CK_CALAMVIEC_TIEN
CHECK (
    TienDauCa >= 0
    AND TienCuoiCa >= 0
    AND SoTienThatThoat >= 0
);

ALTER TABLE CALAMVIEC DROP CONSTRAINT IF EXISTS CK_CALAMVIEC_THOIGIAN;
ALTER TABLE CALAMVIEC
ADD CONSTRAINT CK_CALAMVIEC_THOIGIAN
CHECK (
    ThoiGianDong IS NULL
    OR ThoiGianDong > ThoiGianMo
);


/* =========================================================
   13. HÓA ĐƠN
   ========================================================= */

ALTER TABLE HOADON DROP CONSTRAINT IF EXISTS CK_HOADON_TIEN;
ALTER TABLE HOADON
ADD CONSTRAINT CK_HOADON_TIEN
CHECK (
    TongTien >= 0
    AND TienGiam >= 0
    AND TongTienSauGiam >= 0
    AND TienGiam <= TongTien
);


ALTER TABLE HOADON DROP CONSTRAINT IF EXISTS CK_HOADON_TRANGTHAI;
ALTER TABLE HOADON
ADD CONSTRAINT CK_HOADON_TRANGTHAI
CHECK (TrangThai IN (0, 1, 2, 3));


/* =========================================================
   14. CHI TIẾT HÓA ĐƠN
   ========================================================= */

ALTER TABLE CTHD DROP CONSTRAINT IF EXISTS CK_CTHD_SOLUONG;
ALTER TABLE CTHD
ADD CONSTRAINT CK_CTHD_SOLUONG
CHECK (SoLuong > 0);

ALTER TABLE CTHD DROP CONSTRAINT IF EXISTS CK_CTHD_GIA;
ALTER TABLE CTHD
ADD CONSTRAINT CK_CTHD_GIA
CHECK (GiaBanTaiThoiDiem >= 0);

ALTER TABLE CTHD DROP CONSTRAINT IF EXISTS CK_CTHD_KHONG_TU_LAM_TOPPING;
ALTER TABLE CTHD
ADD CONSTRAINT CK_CTHD_KHONG_TU_LAM_TOPPING
CHECK (
    IDMonChinh IS NULL
    OR IDMonChinh <> ID
);


/* =========================================================
   15. THANH TOÁN
   ========================================================= */

ALTER TABLE THANHTOAN DROP CONSTRAINT IF EXISTS CK_THANHTOAN_PHUONGTHUC;
ALTER TABLE THANHTOAN
ADD CONSTRAINT CK_THANHTOAN_PHUONGTHUC
CHECK (
    PhuongThuc IN (
        'CASH',
        'CARD',
        'MOMO',
        'BANKING',
        'OTHER'
    )
);

ALTER TABLE THANHTOAN DROP CONSTRAINT IF EXISTS CK_THANHTOAN_SOTIEN;
ALTER TABLE THANHTOAN
ADD CONSTRAINT CK_THANHTOAN_SOTIEN
CHECK (SoTien >= 0);

ALTER TABLE THANHTOAN DROP CONSTRAINT IF EXISTS CK_THANHTOAN_TRANGTHAI;
ALTER TABLE THANHTOAN
ADD CONSTRAINT CK_THANHTOAN_TRANGTHAI
CHECK (TrangThai IN (0, 1, 2));


/* =========================================================
   16. TỒN KHO
   ========================================================= */

ALTER TABLE TONKHO DROP CONSTRAINT IF EXISTS CK_TONKHO_SOLUONG;
ALTER TABLE TONKHO
ADD CONSTRAINT CK_TONKHO_SOLUONG
CHECK (SoLuongTon >= 0);


/* =========================================================
   17. LÔ HÀNG
   ========================================================= */

ALTER TABLE LOHANG DROP CONSTRAINT IF EXISTS CK_LOHANG_SOLUONG;
ALTER TABLE LOHANG
ADD CONSTRAINT CK_LOHANG_SOLUONG
CHECK (SoLuongCon >= 0);

ALTER TABLE LOHANG DROP CONSTRAINT IF EXISTS CK_LOHANG_HSD;
ALTER TABLE LOHANG
ADD CONSTRAINT CK_LOHANG_HSD
CHECK (
    HSD IS NULL
    OR HSD >= NgayNhap::DATE
);


/* =========================================================
   18. KIỂM KHO
   ========================================================= */

ALTER TABLE KIEMKHO DROP CONSTRAINT IF EXISTS CK_KIEMKHO_TRANGTHAI;
ALTER TABLE KIEMKHO
ADD CONSTRAINT CK_KIEMKHO_TRANGTHAI
CHECK (TrangThai IN (0, 1, 2));

ALTER TABLE CTKK DROP CONSTRAINT IF EXISTS CK_CTKK_SOLUONG;
ALTER TABLE CTKK
ADD CONSTRAINT CK_CTKK_SOLUONG
CHECK (
    SoLuongHeThong >= 0
    AND SoLuongThucTe >= 0
);

ALTER TABLE CTKK DROP CONSTRAINT IF EXISTS CK_CTKK_CHENHLECH;
ALTER TABLE CTKK
ADD CONSTRAINT CK_CTKK_CHENHLECH
CHECK (ChenhLech = SoLuongThucTe - SoLuongHeThong);


/* =========================================================
   19. PHIẾU NHẬP
   ========================================================= */

ALTER TABLE PHIEUNHAP DROP CONSTRAINT IF EXISTS CK_PHIEUNHAP_TONGTIEN;
ALTER TABLE PHIEUNHAP
ADD CONSTRAINT CK_PHIEUNHAP_TONGTIEN
CHECK (TongTien >= 0);

ALTER TABLE PHIEUNHAP DROP CONSTRAINT IF EXISTS CK_PHIEUNHAP_TRANGTHAI;
ALTER TABLE PHIEUNHAP
ADD CONSTRAINT CK_PHIEUNHAP_TRANGTHAI
CHECK (TrangThai IN (0, 1, 2));

ALTER TABLE CTPN DROP CONSTRAINT IF EXISTS CK_CTPN_TIEN;
ALTER TABLE CTPN
ADD CONSTRAINT CK_CTPN_TIEN
CHECK (
    SoLuong > 0
    AND DonGiaNhap >= 0
    AND ThanhTien >= 0
);



/* =========================================================
   20. PHIẾU XUẤT
   ========================================================= */

ALTER TABLE PHIEUXUAT DROP CONSTRAINT IF EXISTS CK_PHIEUXUAT_TRANGTHAI;
ALTER TABLE PHIEUXUAT
ADD CONSTRAINT CK_PHIEUXUAT_TRANGTHAI
CHECK (TrangThai IN (0, 1, 2));

ALTER TABLE CTPX DROP CONSTRAINT IF EXISTS CK_CTPX_SOLUONG;
ALTER TABLE CTPX
ADD CONSTRAINT CK_CTPX_SOLUONG
CHECK (SoLuong > 0);


/* =========================================================
   21. PHIẾU CHUYỂN
   ========================================================= */

ALTER TABLE PHIEUCHUYEN DROP CONSTRAINT IF EXISTS CK_PHIEUCHUYEN_CHINHANH;
ALTER TABLE PHIEUCHUYEN
ADD CONSTRAINT CK_PHIEUCHUYEN_CHINHANH
CHECK (MaCN_Xuat <> MaCN_Nhap);

ALTER TABLE PHIEUCHUYEN DROP CONSTRAINT IF EXISTS CK_PHIEUCHUYEN_TRANGTHAI;
ALTER TABLE PHIEUCHUYEN
ADD CONSTRAINT CK_PHIEUCHUYEN_TRANGTHAI
CHECK (TrangThai IN (0, 1, 2, 3));

ALTER TABLE CTPC DROP CONSTRAINT IF EXISTS CK_CTPC_SOLUONG;
ALTER TABLE CTPC
ADD CONSTRAINT CK_CTPC_SOLUONG
CHECK (SoLuong > 0);


/* =========================================================
   22. INVENTORY TRANSACTION
   ========================================================= */

ALTER TABLE INVENTORYTRANSACTION DROP CONSTRAINT IF EXISTS CK_INVENTORY_LOAICHUNGTU;
ALTER TABLE INVENTORYTRANSACTION
ADD CONSTRAINT CK_INVENTORY_LOAICHUNGTU
CHECK (
    LoaiChungTu IS NULL
    OR LoaiChungTu IN (
        'HOADON',
        'PHIEUNHAP',
        'PHIEUXUAT',
        'PHIEUCHUYEN',
        'KIEMKHO'
    )
);

ALTER TABLE INVENTORYTRANSACTION DROP CONSTRAINT IF EXISTS CK_INVENTORY_LOAIGD;
ALTER TABLE INVENTORYTRANSACTION
ADD CONSTRAINT CK_INVENTORY_LOAIGD
CHECK (LoaiGiaoDich IN (1, 2, 3, 4, 5));

ALTER TABLE INVENTORYTRANSACTION DROP CONSTRAINT IF EXISTS CK_INVENTORY_SOLUONG;
ALTER TABLE INVENTORYTRANSACTION
ADD CONSTRAINT CK_INVENTORY_SOLUONG
CHECK (SoLuong > 0);

ALTER TABLE INVENTORYTRANSACTION DROP CONSTRAINT IF EXISTS CK_INVENTORY_TRANGTHAI;
ALTER TABLE INVENTORYTRANSACTION
ADD CONSTRAINT CK_INVENTORY_TRANGTHAI
CHECK (TrangThai IN (0, 1));


/* =========================================================
   23. SYNC LOG
   ========================================================= */

ALTER TABLE SYNCLOG DROP CONSTRAINT IF EXISTS CK_SYNCLOG_TRANGTHAI;
ALTER TABLE SYNCLOG
ADD CONSTRAINT CK_SYNCLOG_TRANGTHAI
CHECK (
    TrangThai IN (
        'PENDING',
        'SUCCESS',
        'FAILED',
        'CONFLICT'
    )
);

ALTER TABLE SYNCLOG DROP CONSTRAINT IF EXISTS CK_SYNCLOG_THUCTHE_NOT_EMPTY;
ALTER TABLE SYNCLOG
ADD CONSTRAINT CK_SYNCLOG_THUCTHE_NOT_EMPTY
CHECK (
    ThucThe IS NULL
    OR LENGTH(TRIM(ThucThe)) > 0
);

ALTER TABLE SYNCLOG DROP CONSTRAINT IF EXISTS CK_SYNCLOG_RECORD_NOT_EMPTY;
ALTER TABLE SYNCLOG
ADD CONSTRAINT CK_SYNCLOG_RECORD_NOT_EMPTY
CHECK (
    RecordID IS NULL
    OR LENGTH(TRIM(RecordID)) > 0
);


/* =========================================================
   24. CONFLICT LOG
   ========================================================= */

ALTER TABLE CONFLICTLOG DROP CONSTRAINT IF EXISTS CK_CONFLICTLOG_TRANGTHAI;
ALTER TABLE CONFLICTLOG
ADD CONSTRAINT CK_CONFLICTLOG_TRANGTHAI
CHECK (
    TrangThai IN (
        'UNRESOLVED',
        'RESOLVED_LOCAL',
        'RESOLVED_SERVER',
        'RESOLVED_MANUAL'
    )
);

ALTER TABLE CONFLICTLOG DROP CONSTRAINT IF EXISTS CK_CONFLICTLOG_THUCTHE_NOT_EMPTY;
ALTER TABLE CONFLICTLOG
ADD CONSTRAINT CK_CONFLICTLOG_THUCTHE_NOT_EMPTY
CHECK (
    ThucThe IS NULL
    OR LENGTH(TRIM(ThucThe)) > 0
);

ALTER TABLE CONFLICTLOG DROP CONSTRAINT IF EXISTS CK_CONFLICTLOG_RECORD_NOT_EMPTY;
ALTER TABLE CONFLICTLOG
ADD CONSTRAINT CK_CONFLICTLOG_RECORD_NOT_EMPTY
CHECK (
    RecordID IS NULL
    OR LENGTH(TRIM(RecordID)) > 0
);


/* =========================================================
   25. AUDIT LOG
   ========================================================= */

ALTER TABLE AUDITLOG DROP CONSTRAINT IF EXISTS CK_AUDITLOG_HANHDONG;
ALTER TABLE AUDITLOG
ADD CONSTRAINT CK_AUDITLOG_HANHDONG
CHECK (
    HanhDong IN (
        'INSERT',
        'UPDATE',
        'DELETE'
    )
);

ALTER TABLE AUDITLOG DROP CONSTRAINT IF EXISTS CK_AUDITLOG_THUCTHE_NOT_EMPTY;
ALTER TABLE AUDITLOG
ADD CONSTRAINT CK_AUDITLOG_THUCTHE_NOT_EMPTY
CHECK (
    ThucThe IS NULL
    OR LENGTH(TRIM(ThucThe)) > 0
);

ALTER TABLE AUDITLOG DROP CONSTRAINT IF EXISTS CK_AUDITLOG_RECORD_NOT_EMPTY;
ALTER TABLE AUDITLOG
ADD CONSTRAINT CK_AUDITLOG_RECORD_NOT_EMPTY
CHECK (
    RecordID IS NULL
    OR LENGTH(TRIM(RecordID)) > 0
);