/* =========================================================
   02_CONSTRAINT_INDEX_FIXED.SQL
   Bổ sung UNIQUE và INDEX cho PostgreSQL.
   Lưu ý: trạng thái dùng dạng chữ, không dùng 0/1.
   ========================================================= */

BEGIN;

ALTER TABLE CHINHANH DROP CONSTRAINT IF EXISTS UQ_CHINHANH_TEN;
ALTER TABLE CHINHANH ADD CONSTRAINT UQ_CHINHANH_TEN UNIQUE (TenCN);

ALTER TABLE DONVI DROP CONSTRAINT IF EXISTS UQ_DONVI_TEN;
ALTER TABLE DONVI ADD CONSTRAINT UQ_DONVI_TEN UNIQUE (TenDonVi);

ALTER TABLE NHACUNGCAP DROP CONSTRAINT IF EXISTS UQ_NHACUNGCAP_TEN;
ALTER TABLE NHACUNGCAP ADD CONSTRAINT UQ_NHACUNGCAP_TEN UNIQUE (TenNCC);

ALTER TABLE SANPHAM DROP CONSTRAINT IF EXISTS UQ_SANPHAM_TEN;
ALTER TABLE SANPHAM ADD CONSTRAINT UQ_SANPHAM_TEN UNIQUE (TenSP);

ALTER TABLE NGUYENLIEU DROP CONSTRAINT IF EXISTS UQ_NGUYENLIEU_TEN;
ALTER TABLE NGUYENLIEU ADD CONSTRAINT UQ_NGUYENLIEU_TEN UNIQUE (TenNL);

ALTER TABLE TAIKHOAN DROP CONSTRAINT IF EXISTS UQ_TAIKHOAN_USERNAME;
ALTER TABLE TAIKHOAN ADD CONSTRAINT UQ_TAIKHOAN_USERNAME UNIQUE (Username);

CREATE INDEX IF NOT EXISTS IDX_NHANVIEN_MACN ON NHANVIEN(MaCN);
CREATE INDEX IF NOT EXISTS IDX_TAIKHOAN_USERNAME ON TAIKHOAN(Username);
CREATE INDEX IF NOT EXISTS IDX_TAIKHOAN_MANV ON TAIKHOAN(MaNV);
CREATE INDEX IF NOT EXISTS IDX_TAIKHOAN_VAITRO ON TAIKHOAN(VaiTro);
CREATE INDEX IF NOT EXISTS IDX_KHUYENMAI_THOIGIAN ON KHUYENMAI(NgayBatDau, NgayKetThuc);
CREATE INDEX IF NOT EXISTS IDX_HOADON_MACN_CREATEDAT ON HOADON(MaCN, CreatedAt);
CREATE INDEX IF NOT EXISTS IDX_HOADON_TRANGTHAI ON HOADON(TrangThai);
CREATE INDEX IF NOT EXISTS IDX_HOADON_MACA ON HOADON(MaCa);
CREATE INDEX IF NOT EXISTS IDX_CTHD_MAHD ON CTHD(MaHD);
CREATE INDEX IF NOT EXISTS IDX_CTHD_MASP ON CTHD(MaSP);
CREATE INDEX IF NOT EXISTS IDX_THANHTOAN_MAHD ON THANHTOAN(MaHD);
CREATE INDEX IF NOT EXISTS IDX_THANHTOAN_CREATEDAT ON THANHTOAN(CreatedAt);
CREATE INDEX IF NOT EXISTS IDX_LOHANG_MACN_MANL_HSD ON LOHANG(MaCN, MaNL, HSD, NgayNhap);
CREATE INDEX IF NOT EXISTS IDX_TONKHO_MACN_MANL ON TONKHO(MaCN, MaNL);
CREATE INDEX IF NOT EXISTS IDX_PHIEUNHAP_MACN_NGAYNHAP ON PHIEUNHAP(MaCN, NgayNhap);
CREATE INDEX IF NOT EXISTS IDX_PHIEUXUAT_MACN_CREATEDAT ON PHIEUXUAT(MaCN, CreatedAt);
CREATE INDEX IF NOT EXISTS IDX_PHIEUCHUYEN_XUAT_NHAP ON PHIEUCHUYEN(MaCN_Xuat, MaCN_Nhap);
CREATE INDEX IF NOT EXISTS IDX_KIEMKHO_MACN_NGAYKIEM ON KIEMKHO(MaCN, NgayKiem);
CREATE INDEX IF NOT EXISTS IDX_INVENTORY_MACN_MANL_CREATEDAT ON INVENTORYTRANSACTION(MaCN, MaNL, CreatedAt);
CREATE INDEX IF NOT EXISTS IDX_SYNCLOG_STATUS_CREATED ON SYNCLOG(TrangThai, CreatedAt);
CREATE INDEX IF NOT EXISTS IDX_SYNCLOG_THUCTHE_RECORD ON SYNCLOG(ThucThe, RecordID);
CREATE INDEX IF NOT EXISTS IDX_CONFLICTLOG_STATUS ON CONFLICTLOG(TrangThai);
CREATE INDEX IF NOT EXISTS IDX_CONFLICTLOG_THUCTHE_RECORD ON CONFLICTLOG(ThucThe, RecordID);
CREATE INDEX IF NOT EXISTS IDX_AUDITLOG_THUCTHE_RECORD ON AUDITLOG(ThucThe, RecordID);
CREATE INDEX IF NOT EXISTS IDX_AUDITLOG_CREATEDAT ON AUDITLOG(CreatedAt);

COMMIT;
