/* =========================================================
   01_CREATETABLE_FIXED.SQL
   DATABASE: PHUNG LOC COFFEE - POSTGRESQL
   Mục tiêu: POS bán hàng, công thức pha chế, kho nhiều chi nhánh,
             offline sync, báo cáo doanh thu/tồn kho.
   ========================================================= */

BEGIN;

DROP TABLE IF EXISTS AUDITLOG CASCADE;
DROP TABLE IF EXISTS CONFLICTLOG CASCADE;
DROP TABLE IF EXISTS SYNCLOG CASCADE;
DROP TABLE IF EXISTS INVENTORYTRANSACTION CASCADE;
DROP TABLE IF EXISTS CTPC CASCADE;
DROP TABLE IF EXISTS PHIEUCHUYEN CASCADE;
DROP TABLE IF EXISTS CTPX CASCADE;
DROP TABLE IF EXISTS PHIEUXUAT CASCADE;
DROP TABLE IF EXISTS CTPN CASCADE;
DROP TABLE IF EXISTS PHIEUNHAP CASCADE;
DROP TABLE IF EXISTS CTKK CASCADE;
DROP TABLE IF EXISTS KIEMKHO CASCADE;
DROP TABLE IF EXISTS LOHANG CASCADE;
DROP TABLE IF EXISTS TONKHO CASCADE;
DROP TABLE IF EXISTS THANHTOAN CASCADE;
DROP TABLE IF EXISTS CTHD CASCADE;
DROP TABLE IF EXISTS HOADON CASCADE;
DROP TABLE IF EXISTS CALAMVIEC CASCADE;
DROP TABLE IF EXISTS DINHMUCCONGTHUC CASCADE;
DROP TABLE IF EXISTS PHIENBANCONGTHUC CASCADE;
DROP TABLE IF EXISTS QUYDOIDONVI CASCADE;
DROP TABLE IF EXISTS NGUYENLIEU_DONVI CASCADE;
DROP TABLE IF EXISTS NGUYENLIEU CASCADE;
DROP TABLE IF EXISTS TAIKHOAN CASCADE;
DROP TABLE IF EXISTS NHANVIEN CASCADE;
DROP TABLE IF EXISTS KHUYENMAI CASCADE;
DROP TABLE IF EXISTS SANPHAM CASCADE;
DROP TABLE IF EXISTS NHACUNGCAP CASCADE;
DROP TABLE IF EXISTS DONVI CASCADE;
DROP TABLE IF EXISTS CHINHANH CASCADE;

CREATE TABLE CHINHANH (
    MaCN VARCHAR(20) PRIMARY KEY,
    TenCN VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(255),
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoạt động',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_CHINHANH_TRANGTHAI CHECK (TrangThai IN ('Hoạt động', 'Ngưng hoạt động')),
    CONSTRAINT CK_CHINHANH_TEN CHECK (LENGTH(TRIM(TenCN)) > 0)
);

CREATE TABLE DONVI (
    MaDV VARCHAR(20) PRIMARY KEY,
    TenDonVi VARCHAR(50) NOT NULL,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoạt động',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_DONVI_TRANGTHAI CHECK (TrangThai IN ('Hoạt động', 'Ngưng hoạt động')),
    CONSTRAINT CK_DONVI_TEN CHECK (LENGTH(TRIM(TenDonVi)) > 0)
);

CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR(50) PRIMARY KEY,
    TenNCC VARCHAR(150) NOT NULL,
    SDT VARCHAR(20),
    DiaChi VARCHAR(255),
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoạt động',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_NHACUNGCAP_TRANGTHAI CHECK (TrangThai IN ('Hoạt động', 'Ngưng hoạt động')),
    CONSTRAINT CK_NHACUNGCAP_TEN CHECK (LENGTH(TRIM(TenNCC)) > 0)
);

CREATE TABLE SANPHAM (
    MaSP VARCHAR(50) PRIMARY KEY,
    TenSP VARCHAR(150) NOT NULL,
    GiaHienTai NUMERIC(18,0) NOT NULL DEFAULT 0,
    IsTopping BOOLEAN NOT NULL DEFAULT FALSE,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoạt động',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_SANPHAM_GIA CHECK (GiaHienTai >= 0),
    CONSTRAINT CK_SANPHAM_TRANGTHAI CHECK (TrangThai IN ('Hoạt động', 'Ngưng hoạt động')),
    CONSTRAINT CK_SANPHAM_TEN CHECK (LENGTH(TRIM(TenSP)) > 0)
);

CREATE TABLE KHUYENMAI (
    MaKM VARCHAR(50) PRIMARY KEY,
    TenKM VARCHAR(150) NOT NULL,
    LoaiKM VARCHAR(20) NOT NULL,
    GiaTri NUMERIC(18,2) NOT NULL,
    DieuKienToiThieu NUMERIC(18,0) NOT NULL DEFAULT 0,
    GiaTriGiamToiDa NUMERIC(18,0),
    NgayBatDau TIMESTAMP NOT NULL,
    NgayKetThuc TIMESTAMP NOT NULL,
    SoLuong INT,
    SoLuongDaDung INT NOT NULL DEFAULT 0,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoạt động',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_KHUYENMAI_LOAI CHECK (LoaiKM IN ('PERCENT', 'AMOUNT')),
    CONSTRAINT CK_KHUYENMAI_GIATRI CHECK (GiaTri > 0),
    CONSTRAINT CK_KHUYENMAI_PERCENT CHECK (LoaiKM <> 'PERCENT' OR GiaTri <= 100),
    CONSTRAINT CK_KHUYENMAI_DIEUKIEN CHECK (DieuKienToiThieu >= 0),
    CONSTRAINT CK_KHUYENMAI_SOLUONG CHECK (SoLuong IS NULL OR SoLuong >= 0),
    CONSTRAINT CK_KHUYENMAI_DADUNG CHECK (SoLuongDaDung >= 0),
    CONSTRAINT CK_KHUYENMAI_TRANGTHAI CHECK (TrangThai IN ('Hoạt động', 'Ngưng hoạt động')),
    CONSTRAINT CK_KHUYENMAI_THOIGIAN CHECK (NgayKetThuc > NgayBatDau)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(50) PRIMARY KEY,
    TenNV VARCHAR(100) NOT NULL,
    SDT VARCHAR(20),
    ChucVu VARCHAR(50),
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoạt động',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_NHANVIEN_TRANGTHAI CHECK (TrangThai IN ('Hoạt động', 'Ngưng hoạt động')),
    CONSTRAINT CK_NHANVIEN_TEN CHECK (LENGTH(TRIM(TenNV)) > 0)
);

CREATE TABLE TAIKHOAN (
    MaTK VARCHAR(50) PRIMARY KEY,
    MaNV VARCHAR(50) UNIQUE REFERENCES NHANVIEN(MaNV),
    Username VARCHAR(50) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    VaiTro VARCHAR(30) NOT NULL,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoạt động',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_TAIKHOAN_VAITRO CHECK (VaiTro IN ('ADMIN','QUANLY_CHINHANH','NHANVIEN_BANHANG','NHANVIEN_KHO','KETOAN')),
    CONSTRAINT CK_TAIKHOAN_TRANGTHAI CHECK (TrangThai IN ('Hoạt động', 'Ngưng hoạt động')),
    CONSTRAINT CK_TAIKHOAN_USERNAME CHECK (LENGTH(TRIM(Username)) >= 4),
    CONSTRAINT CK_TAIKHOAN_PASSWORD CHECK (LENGTH(TRIM(PasswordHash)) > 0)
);

CREATE TABLE NGUYENLIEU (
    MaNL VARCHAR(50) PRIMARY KEY,
    TenNL VARCHAR(150) NOT NULL,
    DonViCoBan VARCHAR(20) NOT NULL REFERENCES DONVI(MaDV),
    TonToiThieu NUMERIC(18,2) NOT NULL DEFAULT 0,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoạt động',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_NGUYENLIEU_TONTOITHIEU CHECK (TonToiThieu >= 0),
    CONSTRAINT CK_NGUYENLIEU_TRANGTHAI CHECK (TrangThai IN ('Hoạt động', 'Ngưng hoạt động')),
    CONSTRAINT CK_NGUYENLIEU_TEN CHECK (LENGTH(TRIM(TenNL)) > 0)
);

CREATE TABLE NGUYENLIEU_DONVI (
    MaNL VARCHAR(50) REFERENCES NGUYENLIEU(MaNL) ON DELETE CASCADE,
    MaDV VARCHAR(20) REFERENCES DONVI(MaDV),
    PRIMARY KEY (MaNL, MaDV)
);

CREATE TABLE QUYDOIDONVI (
    MaDV_From VARCHAR(20) REFERENCES DONVI(MaDV),
    MaDV_To VARCHAR(20) REFERENCES DONVI(MaDV),
    TyLeQuyDoi NUMERIC(18,4) NOT NULL,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoạt động',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaDV_From, MaDV_To),
    CONSTRAINT CK_QUYDOI_KHACDONVI CHECK (MaDV_From <> MaDV_To),
    CONSTRAINT CK_QUYDOI_TYLE CHECK (TyLeQuyDoi > 0),
    CONSTRAINT CK_QUYDOI_TRANGTHAI CHECK (TrangThai IN ('Hoạt động', 'Ngưng hoạt động'))
);

CREATE TABLE PHIENBANCONGTHUC (
    MaPB VARCHAR(50) PRIMARY KEY,
    MaSP VARCHAR(50) NOT NULL REFERENCES SANPHAM(MaSP),
    NgayHieuLuc TIMESTAMP NOT NULL,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoạt động',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_PBCT_TRANGTHAI CHECK (TrangThai IN ('Hoạt động', 'Ngưng hoạt động'))
);

CREATE TABLE DINHMUCCONGTHUC (
    MaPB VARCHAR(50) REFERENCES PHIENBANCONGTHUC(MaPB) ON DELETE CASCADE,
    MaNL VARCHAR(50) REFERENCES NGUYENLIEU(MaNL),
    SoLuong NUMERIC(18,4) NOT NULL,
    PRIMARY KEY (MaPB, MaNL),
    CONSTRAINT CK_DINHMUC_SOLUONG CHECK (SoLuong > 0)
);

CREATE TABLE CALAMVIEC (
    MaCa VARCHAR(50) PRIMARY KEY,
    MaNV VARCHAR(50) NOT NULL REFERENCES NHANVIEN(MaNV),
    MaCN VARCHAR(20) NOT NULL REFERENCES CHINHANH(MaCN),
    ThoiGianMo TIMESTAMP NOT NULL,
    ThoiGianDong TIMESTAMP,
    TienDauCa NUMERIC(18,0) NOT NULL DEFAULT 0,
    TienCuoiCa NUMERIC(18,0) NOT NULL DEFAULT 0,
    SoTienThatThoat NUMERIC(18,0) NOT NULL DEFAULT 0,
    LyDoGiaiTrinh VARCHAR(255),
    IsSynced BOOLEAN NOT NULL DEFAULT FALSE,
    ClientID VARCHAR(100),
    ClientUpdatedAt TIMESTAMP,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_CALAMVIEC_TIEN CHECK (TienDauCa >= 0 AND TienCuoiCa >= 0 AND SoTienThatThoat >= 0),
    CONSTRAINT CK_CALAMVIEC_THOIGIAN CHECK (ThoiGianDong IS NULL OR ThoiGianDong > ThoiGianMo)
);

CREATE TABLE HOADON (
    MaHD VARCHAR(50) PRIMARY KEY,
    MaCa VARCHAR(50) NOT NULL REFERENCES CALAMVIEC(MaCa),
    MaCN VARCHAR(20) NOT NULL REFERENCES CHINHANH(MaCN),
    MaKM VARCHAR(50) REFERENCES KHUYENMAI(MaKM),
    TongTien NUMERIC(18,0) NOT NULL DEFAULT 0,
    TienGiam NUMERIC(18,0) NOT NULL DEFAULT 0,
    TongTienSauGiam NUMERIC(18,0) NOT NULL DEFAULT 0,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Tạm',
    IsSynced BOOLEAN NOT NULL DEFAULT FALSE,
    ClientID VARCHAR(100),
    ClientUpdatedAt TIMESTAMP,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_HOADON_TIEN CHECK (TongTien >= 0 AND TienGiam >= 0 AND TongTienSauGiam >= 0),
    CONSTRAINT CK_HOADON_TRANGTHAI CHECK (TrangThai IN ('Hủy', 'Tạm', 'Đã thanh toán', 'Hoàn tiền'))
);

CREATE TABLE CTHD (
    ID VARCHAR(50) PRIMARY KEY,
    MaHD VARCHAR(50) NOT NULL REFERENCES HOADON(MaHD) ON DELETE CASCADE,
    MaSP VARCHAR(50) NOT NULL REFERENCES SANPHAM(MaSP),
    IDMonChinh VARCHAR(50) REFERENCES CTHD(ID),
    SoLuong INT NOT NULL,
    GiaBanTaiThoiDiem NUMERIC(18,0) NOT NULL,
    GhiChu VARCHAR(255),
    DaTruKho BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_CTHD_SOLUONG CHECK (SoLuong > 0),
    CONSTRAINT CK_CTHD_GIA CHECK (GiaBanTaiThoiDiem >= 0)
);

CREATE TABLE THANHTOAN (
    MaTT VARCHAR(50) PRIMARY KEY,
    MaHD VARCHAR(50) NOT NULL REFERENCES HOADON(MaHD) ON DELETE CASCADE,
    PhuongThuc VARCHAR(20) NOT NULL,
    SoTien NUMERIC(18,0) NOT NULL,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Chờ thanh toán',
    MaGiaoDichNgoai VARCHAR(100),
    IsSynced BOOLEAN NOT NULL DEFAULT FALSE,
    ClientID VARCHAR(100),
    ClientUpdatedAt TIMESTAMP,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_THANHTOAN_PHUONGTHUC CHECK (PhuongThuc IN ('CASH', 'CARD', 'MOMO', 'BANKING', 'OTHER')),
    CONSTRAINT CK_THANHTOAN_SOTIEN CHECK (SoTien >= 0),
    CONSTRAINT CK_THANHTOAN_TRANGTHAI CHECK (TrangThai IN ('Thất bại', 'Chờ thanh toán', 'Thành công'))
);

CREATE TABLE TONKHO (
    MaCN VARCHAR(20) REFERENCES CHINHANH(MaCN),
    MaNL VARCHAR(50) REFERENCES NGUYENLIEU(MaNL),
    SoLuongTon NUMERIC(18,2) NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaCN, MaNL),
    CONSTRAINT CK_TONKHO_SOLUONG CHECK (SoLuongTon >= 0)
);

CREATE TABLE LOHANG (
    MaLo VARCHAR(50) PRIMARY KEY,
    MaNL VARCHAR(50) NOT NULL REFERENCES NGUYENLIEU(MaNL),
    MaCN VARCHAR(20) NOT NULL REFERENCES CHINHANH(MaCN),
    NgayNhap TIMESTAMP NOT NULL,
    HSD DATE,
    SoLuongCon NUMERIC(18,2) NOT NULL DEFAULT 0,
    IsSynced BOOLEAN NOT NULL DEFAULT FALSE,
    ClientID VARCHAR(100),
    ClientUpdatedAt TIMESTAMP,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_LOHANG_SOLUONG CHECK (SoLuongCon >= 0),
    CONSTRAINT CK_LOHANG_HSD CHECK (HSD IS NULL OR HSD >= NgayNhap::DATE)
);

CREATE TABLE KIEMKHO (
    MaKK VARCHAR(50) PRIMARY KEY,
    MaNV VARCHAR(50) NOT NULL REFERENCES NHANVIEN(MaNV),
    MaCN VARCHAR(20) NOT NULL REFERENCES CHINHANH(MaCN),
    NgayKiem TIMESTAMP NOT NULL,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Đang kiểm',
    DaXuLyKho BOOLEAN NOT NULL DEFAULT FALSE,
    IsSynced BOOLEAN NOT NULL DEFAULT FALSE,
    ClientID VARCHAR(100),
    ClientUpdatedAt TIMESTAMP,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_KIEMKHO_TRANGTHAI CHECK (TrangThai IN ('Hủy', 'Đang kiểm', 'Đã xác nhận'))
);

CREATE TABLE CTKK (
    MaKK VARCHAR(50) REFERENCES KIEMKHO(MaKK) ON DELETE CASCADE,
    MaNL VARCHAR(50) REFERENCES NGUYENLIEU(MaNL),
    SoLuongHeThong NUMERIC(18,2) NOT NULL DEFAULT 0,
    SoLuongThucTe NUMERIC(18,2) NOT NULL DEFAULT 0,
    ChenhLech NUMERIC(18,2) NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaKK, MaNL),
    CONSTRAINT CK_CTKK_SOLUONG CHECK (SoLuongHeThong >= 0 AND SoLuongThucTe >= 0)
);

CREATE TABLE PHIEUNHAP (
    MaPN VARCHAR(50) PRIMARY KEY,
    MaCN VARCHAR(20) NOT NULL REFERENCES CHINHANH(MaCN),
    MaNV VARCHAR(50) NOT NULL REFERENCES NHANVIEN(MaNV),
    MaNCC VARCHAR(50) REFERENCES NHACUNGCAP(MaNCC),
    TongTien NUMERIC(18,0) NOT NULL DEFAULT 0,
    NgayNhap TIMESTAMP NOT NULL,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Nháp',
    DaXuLyKho BOOLEAN NOT NULL DEFAULT FALSE,
    IsSynced BOOLEAN NOT NULL DEFAULT FALSE,
    ClientID VARCHAR(100),
    ClientUpdatedAt TIMESTAMP,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_PHIEUNHAP_TONGTIEN CHECK (TongTien >= 0),
    CONSTRAINT CK_PHIEUNHAP_TRANGTHAI CHECK (TrangThai IN ('Hủy', 'Nháp', 'Đã nhập kho'))
);

CREATE TABLE CTPN (
    MaPN VARCHAR(50) REFERENCES PHIEUNHAP(MaPN) ON DELETE CASCADE,
    MaLo VARCHAR(50) REFERENCES LOHANG(MaLo),
    SoLuong NUMERIC(18,2) NOT NULL,
    DonGiaNhap NUMERIC(18,0) NOT NULL,
    ThanhTien NUMERIC(18,0) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaPN, MaLo),
    CONSTRAINT CK_CTPN_TIEN CHECK (SoLuong > 0 AND DonGiaNhap >= 0 AND ThanhTien >= 0)
);

CREATE TABLE PHIEUXUAT (
    MaPX VARCHAR(50) PRIMARY KEY,
    MaCN VARCHAR(20) NOT NULL REFERENCES CHINHANH(MaCN),
    MaNV VARCHAR(50) NOT NULL REFERENCES NHANVIEN(MaNV),
    LyDo VARCHAR(255),
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Nháp',
    DaXuLyKho BOOLEAN NOT NULL DEFAULT FALSE,
    IsSynced BOOLEAN NOT NULL DEFAULT FALSE,
    ClientID VARCHAR(100),
    ClientUpdatedAt TIMESTAMP,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_PHIEUXUAT_TRANGTHAI CHECK (TrangThai IN ('Hủy', 'Nháp', 'Đã xuất kho'))
);

CREATE TABLE CTPX (
    MaPX VARCHAR(50) REFERENCES PHIEUXUAT(MaPX) ON DELETE CASCADE,
    MaLo VARCHAR(50) REFERENCES LOHANG(MaLo),
    SoLuong NUMERIC(18,2) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaPX, MaLo),
    CONSTRAINT CK_CTPX_SOLUONG CHECK (SoLuong > 0)
);

CREATE TABLE PHIEUCHUYEN (
    MaPC VARCHAR(50) PRIMARY KEY,
    MaCN_Xuat VARCHAR(20) NOT NULL REFERENCES CHINHANH(MaCN),
    MaCN_Nhap VARCHAR(20) NOT NULL REFERENCES CHINHANH(MaCN),
    MaNV VARCHAR(50) NOT NULL REFERENCES NHANVIEN(MaNV),
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Tạo phiếu',
    DaXuLyKho BOOLEAN NOT NULL DEFAULT FALSE,
    DaNhanKho BOOLEAN NOT NULL DEFAULT FALSE,
    IsSynced BOOLEAN NOT NULL DEFAULT FALSE,
    ClientID VARCHAR(100),
    ClientUpdatedAt TIMESTAMP,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_PHIEUCHUYEN_CHINHANH CHECK (MaCN_Xuat <> MaCN_Nhap),
    CONSTRAINT CK_PHIEUCHUYEN_TRANGTHAI CHECK (TrangThai IN ('Hủy', 'Tạo phiếu', 'Đang chuyển', 'Đã nhận'))
);

CREATE TABLE CTPC (
    MaPC VARCHAR(50) REFERENCES PHIEUCHUYEN(MaPC) ON DELETE CASCADE,
    MaLo VARCHAR(50) REFERENCES LOHANG(MaLo),
    SoLuong NUMERIC(18,2) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaPC, MaLo),
    CONSTRAINT CK_CTPC_SOLUONG CHECK (SoLuong > 0)
);

CREATE TABLE INVENTORYTRANSACTION (
    MaTrans VARCHAR(50) PRIMARY KEY,
    MaCN VARCHAR(20) NOT NULL REFERENCES CHINHANH(MaCN),
    MaNL VARCHAR(50) NOT NULL REFERENCES NGUYENLIEU(MaNL),
    MaLo VARCHAR(50) REFERENCES LOHANG(MaLo),
    LoaiChungTu VARCHAR(20) NOT NULL,
    IDChungTu VARCHAR(50) NOT NULL,
    LoaiGiaoDich VARCHAR(30) NOT NULL,
    SoLuong NUMERIC(18,2) NOT NULL,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hợp lệ',
    IsSynced BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_INVENTORY_LOAICHUNGTU CHECK (LoaiChungTu IN ('HOADON','PHIEUNHAP','PHIEUXUAT','PHIEUCHUYEN','KIEMKHO')),
    CONSTRAINT CK_INVENTORY_LOAIGD CHECK (LoaiGiaoDich IN ('NHAP','XUAT','CHUYEN_DI','CHUYEN_DEN','DIEU_CHINH_TANG','DIEU_CHINH_GIAM')),
    CONSTRAINT CK_INVENTORY_SOLUONG CHECK (SoLuong > 0),
    CONSTRAINT CK_INVENTORY_TRANGTHAI CHECK (TrangThai IN ('Hủy', 'Hợp lệ'))
);

CREATE TABLE SYNCLOG (
    SyncID VARCHAR(50) PRIMARY KEY,
    ThucThe VARCHAR(50) NOT NULL,
    RecordID VARCHAR(50) NOT NULL,
    ClientID VARCHAR(100),
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    GhiChu TEXT,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_SYNCLOG_TRANGTHAI CHECK (TrangThai IN ('PENDING', 'SUCCESS', 'FAILED', 'CONFLICT'))
);

CREATE TABLE CONFLICTLOG (
    ConflictID VARCHAR(50) PRIMARY KEY,
    ThucThe VARCHAR(50) NOT NULL,
    RecordID VARCHAR(50) NOT NULL,
    ClientID VARCHAR(100),
    DataLocal JSONB,
    DataServer JSONB,
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'UNRESOLVED',
    GhiChu TEXT,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_CONFLICTLOG_TRANGTHAI CHECK (TrangThai IN ('UNRESOLVED','RESOLVED_LOCAL','RESOLVED_SERVER','RESOLVED_MANUAL'))
);

CREATE TABLE AUDITLOG (
    LogID VARCHAR(50) PRIMARY KEY,
    MaNV VARCHAR(50),
    ThucThe VARCHAR(50) NOT NULL,
    RecordID VARCHAR(50) NOT NULL,
    HanhDong VARCHAR(20) NOT NULL,
    DuLieuCu JSONB,
    DuLieuMoi JSONB,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_AUDITLOG_HANHDONG CHECK (HanhDong IN ('INSERT', 'UPDATE', 'DELETE'))
);

COMMIT;
